[meta]
captured_at = "2026-05-26T16:20:06.959366Z"
harness_version = "0.0.0"
term = "tmux-256color"
term_program = "tmux"
term_program_version = "3.4"
tmux = true
ssh = false

[[capability]]
name = "kitty_keyboard_protocol"
value = "unsupported"
provenance = "query_response"
raw_response = [
    "1b",
    "5b",
    "3f",
    "31",
    "3b",
    "32",
    "3b",
    "34",
    "63",
]

[[keypress]]
intended = "ctrl+a"
mode = "baseline"
raw_bytes = []
expected_key = "Char('a')"
expected_mods = ["CTRL"]

[[keypress]]
intended = "cmd+1"
mode = "baseline"
raw_bytes = []
expected_key = "Char('1')"
expected_mods = ["SUPER"]

[[keypress]]
intended = "alt+a"
mode = "baseline"
raw_bytes = []
expected_key = "Char('a')"
expected_mods = ["ALT"]

[[keypress]]
intended = "ctrl+i"
mode = "baseline"
raw_bytes = ["09"]
read_chunks = [1]
expected_key = "Char('i')"
expected_mods = ["CTRL"]

[[keypress]]
intended = "shift+tab"
mode = "baseline"
raw_bytes = [
    "1b",
    "5b",
    "5a",
]
read_chunks = [3]
expected_key = "Tab"
expected_mods = ["SHIFT"]

[[keypress]]
intended = "f1"
mode = "baseline"
raw_bytes = [
    "1b",
    "4f",
    "50",
]
read_chunks = [3]
expected_key = "F(1)"
expected_mods = []

[[keypress]]
intended = "up"
mode = "baseline"
raw_bytes = [
    "1b",
    "5b",
    "41",
]
read_chunks = [3]
expected_key = "Up"
expected_mods = []

[[keypress]]
intended = "down"
mode = "baseline"
raw_bytes = [
    "1b",
    "5b",
    "42",
]
read_chunks = [3]
expected_key = "Down"
expected_mods = []

[[keypress]]
intended = "left"
mode = "baseline"
raw_bytes = [
    "1b",
    "5b",
    "44",
]
read_chunks = [3]
expected_key = "Left"
expected_mods = []

[[keypress]]
intended = "right"
mode = "baseline"
raw_bytes = [
    "1b",
    "5b",
    "43",
]
read_chunks = [3]
expected_key = "Right"
expected_mods = []

[[keypress]]
intended = "esc"
mode = "baseline"
raw_bytes = ["1b"]
read_chunks = [1]
expected_key = "Esc"
expected_mods = []
